# http://dallery.gallery/wp-content/uploads/2022/07/The-DALL%C2%B7E-2-prompt-book-v1.02.pdf

bank = {
    "Emotions": {
        "Positive mood, low energy": [
            "light",
            "peaceful",
            "calm",
            "serene",
            "soothing",
            "relaxed",
            "placid",
            "comforting",
            "cosy",
            "tranquil",
            "quiet",
            "pastel",
            "delicate",
            "graceful",
            "subtle",
            "balmy",
            "mild",
            "ethereal",
            "elegant",
            "tender",
            "soft",
            "light",
        ],
        "Negative mood, low energy": [
            "muted",
            "bleak",
            "funeral",
            "somber",
            "melancholic",
            "mournful",
            "gloomy",
            "dismal",
            "sad",
            "pale",
            "washed-out",
            "desaturated",
            "grey",
            "subdued",
            "dull",
            "dreary",
            "depressing",
            "weary",
            "tired",
        ],
        "Positive mood, high energy": [
            "bright",
            "vibrant",
            "dynamic",
            "spirited",
            "vivid",
            "lively",
            "energetic",
            "colorful",
            "joyful",
            "romantic",
            "expressive",
            "bright",
            "rich",
            "kaleidoscopic",
            "psychedelic",
            "saturated",
            "ecstatic",
            "brash",
            "exciting",
            "passionate",
            "hot",
        ],
        "Negative mood, high energy": [
            "dark",
            "ominous",
            "threatening",
            "haunting",
            "forbidding",
            "gloomy",
            "stormy",
            "doom",
            "apocalyptic",
            "sinister",
            "shadowy",
            "ghostly",
            "unnerving",
            "harrowing",
            "dreadful",
            "frightful",
            "shocking",
            "terror",
            "hideous",
            "ghastly",
            "terrifying",
        ],
    },
    "Size and Structure": {
        "Big and Free": [
            "curvaceous",
            "swirling",
            "organic",
            "riotous",
            "turbulent",
            "flowing",
            "amorphous",
            "natural",
            "distorted",
            "uneven",
            "random",
            "lush",
            "organic",
            "bold",
            "intuitive",
            "emotive",
            "chaotic",
            "tumultuous",
            "earthy",
            "churning",
        ],
        "Big and Structured": [
            "monumental",
            "imposing",
            "rigorous",
            "geometric",
            "ordered",
            "angular",
            "artificial",
            "lines",
            "straight",
            "rhythmic",
            "composed",
            "unified",
            "manmade",
            "perspective",
            "minimalist",
            "blocks",
            "dignified",
            "robust",
            "defined",
        ],
        "Small and Structured": [
            "ornate",
            "delicate",
            "neat",
            "precise",
            "detailed",
            "opulent",
            "lavish",
            "elegant",
            "ornamented",
            "fine",
            "elaborate",
            "accurate",
            "intricate",
            "meticulous",
            "decorative",
            "realistic",
        ],
        "Small and Free": [
            "uplanned",
            "daring",
            "brash",
            "random",
            "casual",
            "sketched",
            "playful",
            "spontaneous",
            "extemporaneous",
            "offhand",
            "improvisational",
            "experimental",
            "loose",
            "jaunty",
            "light",
            "expressive",
        ],
    },
    "Vibes": {
        "Vaporwave": ["neon", "pink", "blue", "geometric", "futuristic", "'80s"],
        "Post-apocalyptic": ["grey", "desolate", "stormy", "fire", "decay"],
        "Memphis": ["Memphis Group", "1980s", "bold", "kitch", "colourful", "shapes"],
        "Fantasy": ["stone", "dark", "lush", "nature", "mist", "mystery", "angular"],
        "Dieselpunk": ["grimy", "steel", "oil", "'50s", "mechanised"],
        "Science Fiction": ["glows", "greens", "metals", "armor", "chrome"],
        "Cyberpunk": ["1990s", "dyedhair", "spiky", "graphicelements"],
        "Steampunk": ["gold", "copper", "brass", "Victoriana"],
        "Biopunk": ["greens", "slimes", "plants", "futuristic", "weird"],
    },
    "Photography": [
        "extreme close-up shot",
        "medium shot",
        "midshot",
        "long shot",
        "wide shot",
        "full shot",
        "extreme wide shot",
        "film still",
        "high angle",
        "low angle",
        "shot from below",
        "aerial photo",
        "dutch angle",
        "tilted frame",
        "over-the-shoulder shot",
    ],
    "Illustrations": [
        "stencil",
        "street art",
        "Banksy",
        "ballpoint pen",
        "pencil sketch",
        "charcoal sketch",
        "woodcut",
        "etching",
        "crayon",
        "child's drawing",
        "acrylic on canvas",
        "watercolor",
        "coloured pencil",
        "oil painting",
        "pastels",
        "airbush",
        "collage",
        "vector art",
        "screen printing",
        "low poly",
        "layered paper",
        "sticker illustration",
        "storybook",
        "digital painting",
        "isometric 3D",
        "3D render",
        "claymation",
        "felt pieces",
        "perler beads",
        "vintage disney",
        "pixel art",
        "anime",
        "pixar",
        "studio ghibli",
        "hanna barbera",
    ],
}

